spring:
  application:
    name: passportinsuranceservice
  datasource:
    password: 123
    username: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: create
server:
  port: 8081
