spring:
  profiles:
    active: rest
  application:
    name: passportinsuranceservice
  datasource:
    password: 123
    username: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: none
server:
  port: 8081
